name: swift_ids
description: Convert numeric IDs to human friendly hash string that is shorter and easier to write and memorize.
version: 1.1.4
author: Franciszek Szczepan Wawrzak <frank@wawrzak.com>
homepage: https://github.com/fsw/swift_ids
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: any
  hashids2: any
