name: swift_ids
description: Convert numeric IDs to human friendly hash string that is shorter and easier to write and memorize.
version: 2.1.0
homepage: https://github.com/fsw/swift_ids
environment:
  sdk: ">=2.12.0 <4.0.0"
dev_dependencies:
  test: any
  hashids2: any
